#### Write a program to Implement Backpropagation Algorithm

In [ ]:
import numpy as np
from sklearn.neural_network import MLPClassifier

- Backpropagation using sklearn's MLPClassifier

In [ ]:

X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

y = np.array([0, 1, 1, 0])

- Model Tranning part

In [ ]:
model = MLPClassifier(hidden_layer_sizes=(4,),
                      activation='logistic',
                      solver='sgd',
                      learning_rate_init=0.1,
                      max_iter=10000,
                      random_state=1)

model.fit(X, y)

predictions = model.predict(X)
probabilities = model.predict_proba(X)[:, 1]

In [7]:

print('=' * 50)
print('Input data:')
print(X)
print('=' * 50)
print('Predictions:')
print('=' * 50)
print(predictions)
print('=' * 50)
print('Prediction probabilities:')
print('=' * 50)
print(np.round(probabilities, 4))
print('=' * 50)
print('Training accuracy:')
print('=' * 50)
print(model.score(X, y))
print('=' * 50)

Input data:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]
Predictions:
[0 0 1 1]
Prediction probabilities:
[0.4903 0.4951 0.5172 0.5193]
Training accuracy:
0.5
